const translations = {
    ne: {
        nav_services: "सेवाहरू",
        nav_experts: "विशेषज्ञहरू",
        nav_booking: "परामर्श बुक गर्नुहोस्",
        hero_title: "ब्रह्माण्डको ज्ञान, नयाँ शैलीमा",
        hero_subtitle: "पराशरी र जैमिनी ज्योतिषको माध्यमबाट तपाईंको भाग्य बुझ्नुहोस्।",
        btn_book: "जन्म कुण्डली विश्लेषण",
        btn_explore: "सेवाहरू हेर्नुहोस्",
        service_title: "दिव्य सेवाहरू",
        rashi_1_name: "मेष", rashi_1_desc: "विंशोत्तरी दशा विश्लेषण",
        rashi_2_name: "वृष", rashi_2_desc: "नवांश (D9) गहन अध्ययन",
        rashi_3_name: "मिथुन", rashi_3_desc: "मुहूर्त चयन",
        rashi_4_name: "कर्कट", rashi_4_desc: "पारिवारिक वंश आशीर्वाद",
        rashi_5_name: "सिंह", rashi_5_desc: "करियर र शक्ति गतिशीलता",
        rashi_6_name: "कन्या", rashi_6_desc: "स्वास्थ्य र कल्याण वास्तु",
        rashi_7_name: "तुला", rashi_7_desc: "सम्बन्ध सद्भाव",
        rashi_8_name: "वृश्चिक", rashi_8_desc: "कार्मिक ऋण विश्लेषण",
        rashi_9_name: "धनु", rashi_9_desc: "उच्च ज्ञान मार्गदर्शन",
        rashi_10_name: "मकर", rashi_10_desc: "सामाजिक योगदान",
        rashi_11_name: "कुम्भ", rashi_11_desc: "आध्यात्मिक मुक्ति",
        rashi_12_name: "मीन", rashi_12_desc: "विश्वव्यापी मोक्ष मार्ग",
        about_title: "हाम्रो बारेमा",
        approach_pathak: "शास्त्रीय अनुसन्धान र वैज्ञानिक विश्लेषण",
        approach_rupakheti: "परम्परागत शुद्धता र वैदिक संस्कार",
        service_price_tag: "मूल्य:",
        service_duration_tag: "अवधि:",
        booking_mode: "परामर्शको माध्यम",
        mode_phone: "फोन",
        mode_video: "भिडियो",
        mode_inpatient: "व्यक्तिगत भेट",
        testimonials_title: "ग्राहकका अनुभवहरू",
        testimonial_1: "उहाँको भविष्यवाणी एकदमै सटीक थियो। मेरो करियरको लागि उहाँको मार्गदर्शनले ठूलो सहयोग गर्यो।",
        testimonial_1_author: "राम कुमार, काठमाडौं",
        testimonial_2: "विवाह मिलानमा उहाँको गहिरो विश्लेषणले हामीलाई धेरै स्पष्टता दियो। धेरै धेरै धन्यवाद।",
        testimonial_2_author: "सीता गुरुङ, पोखरा",
        faq_title: "बारम्बार सोधिने प्रश्नहरू",
        faq_1_q: "परामर्शको शुल्क कति छ?",
        faq_1_a: "सेवा अनुसार शुल्क फरक छ। विस्तृत विवरण सेवा सेक्सनमा हेर्न सक्नुहुन्छ।",
        faq_2_q: "अनलाइन परामर्श कसरी हुन्छ?",
        faq_2_a: "हामी फोन वा भिडियो कल (Zoom/WhatsApp) मार्फत परामर्श दिन्छौं।",
        contact_title: "सम्पर्क विवरण",
        hours_title: "कार्य समय",
        location_title: "स्थान",
        tools_title: "नि: शुल्क उपकरणहरू",
        tool_horoscope: "दैनिक राशिफल",
        tool_rashi: "तपाईंको राशि फेला पार्नुहोस्",
        stats_experience: "अनुभव (वर्ष)",
        stats_clients: "सन्तुष्ट ग्राहकहरू",
        expert_title: "विद्वान शास्त्रीय परम्परा",
        expert_pathak_badge: "शैक्षिक दक्षता र विद्वत्ता",
        expert_pathak_desc: "ज्योतिष शास्त्रमा विद्यावारिधि (PhD), ३० वर्षभन्दा बढीको अनुसन्धान अनुभव। उहाँको दृष्टिकोण शास्त्रीय र वैज्ञानिक दुवै छ।",
        expert_rupakheti_badge: "परम्परागत ब्राह्मण वंश",
        expert_rupakheti_desc: "बहु-पुस्ताको परम्परागत पञ्चाङ्ग र मुहूर्त शुद्धता। उहाँले प्राचीन वैदिक परम्परालाई आधुनिक समयमा पनि जीवन्त राख्नुभएको छ।",
        booking_title: "परामर्श बुक गर्नुहोस्",
        label_name: "नाम",
        label_dob: "जन्म मिति",
        label_tob: "जन्म समय (सटीक)",
        label_coords: "जन्म स्थान",
        label_tithi: "तिथि",
        label_nakshatra: "नक्षत्र",
        btn_submit: "बुकिङ पुष्टि गर्नुहोस्",
        lang_toggle: "English Translation"
    },
    en: {
        nav_services: "Services",
        nav_experts: "About",
        nav_booking: "Book Now",
        hero_title: "Trusted Vedic Guidance",
        hero_subtitle: "Scientific horoscopy and traditional wisdom for a clearer future.",
        btn_book: "Book Consultation",
        btn_explore: "View Services",
        service_title: "Our Consultations",
        rashi_1_name: "Birth Chart", rashi_1_desc: "Full life analysis & future predictions.",
        rashi_2_name: "Marriage", rashi_2_desc: "Matching (Milan) & relationship harmony.",
        rashi_3_name: "Career", rashi_3_desc: "Job, business, and power dynamics.",
        rashi_4_name: "Travel", rashi_4_desc: "Foreign settlement & education abroad.",
        rashi_5_name: "Health", rashi_5_desc: "Ayurvedic astrology & wellness peaks.",
        rashi_6_name: "Vastu", rashi_6_desc: "Home & workplace energy alignment.",
        rashi_7_name: "Gemstones", rashi_7_desc: "Planetary remediation through gems.",
        rashi_8_name: "Muhurta", rashi_8_desc: "Auspicious timing for new starts.",
        rashi_9_name: "Numerology", rashi_9_desc: "Power of numbers in your life.",
        rashi_10_name: "Children", rashi_10_desc: "Parenting & educational path analysis.",
        rashi_11_name: "Business", rashi_11_desc: "Profitability & growth cycles.",
        rashi_12_name: "Spirituality", rashi_12_desc: "Karmic path & Moksha guidance.",
        about_title: "Meet the Experts",
        approach_pathak: "Academic Research & Logical Deduction",
        approach_rupakheti: "Ancestral Precision & Vedic Integrity",
        service_price_tag: "Price:",
        service_duration_tag: "Duration:",
        booking_mode: "Consultation Mode",
        mode_phone: "Phone Call",
        mode_video: "Video Meeting",
        mode_inpatient: "In-Person",
        testimonials_title: "Client Testimonials",
        testimonial_1: "The predictions were incredibly accurate. His guidance for my career change was a turning point.",
        testimonial_1_author: "Ram Kumar, Kathmandu",
        testimonial_2: "Deeply insightful marriage compatibility analysis. It gave us so much clarity. Highly recommended.",
        testimonial_2_author: "Sita Gurung, Pokhara",
        faq_title: "Frequently Asked Questions",
        faq_1_q: "What is the consultation fee?",
        faq_1_a: "Fees vary by service. Please refer to our services section for transparent pricing.",
        faq_2_q: "How do online consultations work?",
        faq_2_a: "We offer consultations via phone or video calls (Zoom/WhatsApp) for your convenience.",
        contact_title: "Get In Touch",
        hours_title: "Working Hours",
        location_title: "Our Location",
        tools_title: "Free Astro Tools",
        tool_horoscope: "Daily Horoscope",
        tool_rashi: "Find Your Zodiac",
        stats_experience: "Years Practice",
        stats_clients: "Clients Served",
        expert_title: "Scholarly Traditional Wisdom",
        expert_pathak_badge: "Academic Mastery",
        expert_pathak_desc: "PhD in Vedic Astrology with 30+ years of research. Dr. Pathak blends academic rigor with predictive precision.",
        expert_rupakheti_badge: "Lineage Excellence",
        expert_rupakheti_desc: "Upholding a multi-generational legacy of Panchang. Mr. Rupakheti represents the purest traditional lineage of Nepali Jyotish.",
        booking_title: "Secure Booking Portal",
        label_name: "Name",
        label_dob: "Birth Date",
        label_tob: "Exact Time",
        label_coords: "Birth Location",
        label_tithi: "Tithi",
        label_nakshatra: "Nakshatra",
        btn_submit: "Confirm Booking",
        lang_toggle: "नेपाली"
    }
};

let currentLang = 'ne';

function updateLanguage(lang) {
    currentLang = lang;
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        el.textContent = translations[lang][key];
    });
    document.getElementById('lang-toggle').textContent = translations[lang].lang_toggle;
    document.documentElement.lang = lang;
}

document.getElementById('lang-toggle').addEventListener('click', () => {
    updateLanguage(currentLang === 'ne' ? 'en' : 'ne');
});
